import { telemedicineApi } from "../../API/endpoints/telemedicineApi.js";

export const telemedicineService = {
  createSession: (payload) => telemedicineApi.createSession(payload),
  listSessions: (params = {}) => telemedicineApi.listSessions(params),
  getSessionById: (id) => telemedicineApi.getSessionById(id),
  getSessionBySessionId: (sessionId) => telemedicineApi.getSessionBySessionId(sessionId),
  updateSession: (id, payload) => telemedicineApi.updateSession(id, payload),
  deleteSession: (id) => telemedicineApi.deleteSession(id),
  startSession: (id) => telemedicineApi.startSession(id),
  pauseSession: (id) => telemedicineApi.pauseSession(id),
  resumeSession: (id) => telemedicineApi.resumeSession(id),
  completeSession: (id, params) => telemedicineApi.completeSession(id, params),
  cancelSession: (id, params) => telemedicineApi.cancelSession(id, params),
  terminateSession: (id, params) => telemedicineApi.terminateSession(id, params),
  rateSession: (id, params) => telemedicineApi.rateSession(id, params),
  getSessionsWithFilters: (params = {}) => telemedicineApi.getSessionsWithFilters(params),
  getSessionsByStatus: (status, params = {}) => telemedicineApi.getSessionsByStatus(status, params),
  getSessionsByPlatform: (platform, params = {}) => telemedicineApi.getSessionsByPlatform(platform, params),
  getSessionsByPriority: (priority) => telemedicineApi.getSessionsByPriority(priority),
  searchSessions: (params = {}) => telemedicineApi.searchSessions(params),
  getPlatformOverview: () => telemedicineApi.getOverview(),
  getRevenueData: (params = {}) => telemedicineApi.getRevenueData(params),
  getPlatformStats: () => telemedicineApi.getPlatformStats(),
  getUsageDistribution: () => telemedicineApi.getUsageDistribution(),
  getRecentActivity: (params = {}) => telemedicineApi.getRecentActivity(params),
  getOnlineDoctors: () => telemedicineApi.getOnlineDoctors(),
  getSessionHistory: (params = {}) => telemedicineApi.getHistory(params),
};
